#!/usr/bin/env python3
from pathlib import Path
from html import escape
ROOT=Path(__file__).parent
BOOK='https://dashboard.boulevard.io/booking/businesses/9bf461e1-913f-4005-9f23-ac457d7a3747/widget#/locations'
PAGES={
'brazilian-laser-hair-removal-clearfield-ut.html':('Brazilian Laser Hair Removal Clearfield UT','Brazilian Laser Hair Removal','A consultation-based hair-reduction service for the Brazilian area with preparation, session timing and aftercare guidance.','/laserhairremoval.html'),
'underarm-laser-hair-removal-clearfield-ut.html':('Underarm Laser Hair Removal Clearfield UT','Underarm Laser Hair Removal','Reduce repeated shaving, dark shadow and irritation with a customized series of underarm treatments.','/laserhairremoval.html'),
'arm-laser-hair-removal-clearfield-ut.html':('Arm Laser Hair Removal Clearfield UT','Arm Laser Hair Removal','Treatment planning for partial or full arms based on hair density, skin response and long-term goals.','/laserhairremoval.html'),
'facial-laser-hair-removal-in-clearfield-ut.html':('Facial Laser Hair Removal Clearfield UT','Facial Laser Hair Removal','Hair-reduction treatment for selected facial areas after review of skin, hair and medical history.','/laserhairremoval.html'),
'forehead-botox.html':('Forehead Botox Clearfield UT','Forehead Botox','Personalized neuromodulator planning based on forehead movement, symmetry and the desired degree of softening.','/botox.html'),
'crows-feet-botox.html':("Crow's Feet Botox Clearfield UT","Crow's Feet Treatment",'Consultation and treatment planning for expression lines around the eyes.','/botox.html'),
'jawline-botox.html':('Jawline Botox Clearfield UT','Jawline and Masseter Botox','Individual assessment for jawline balance, masseter concerns and appropriate treatment goals.','/botox.html'),
'natural-lip-filler.html':('Natural Lip Filler Clearfield UT','Natural-Looking Lip Filler','Consultation-based lip enhancement focused on proportion, balance and an individualized result.','/botox.html'),
'microneedling.html':('Microneedling Clearfield UT','Microneedling','Controlled skin treatment planned around texture, tone, treatment history and appropriate recovery time.','/facials.html'),
'chemicalpeel.html':('Chemical Peels Clearfield UT','Chemical Peels','Professional peel selection based on skin type, current products, sensitivity and treatment goals.','/facials.html'),
'hydrating-facial.html':('Hydrating Facial Clearfield UT','Hydrating Facial','A customized facial focused on cleansing, hydration and supporting the skin barrier.','/facials.html'),
'ipl-photofacial.html':('IPL Photofacial Clearfield UT','IPL Photofacial','Light-based consultation and treatment planning for appropriate concerns involving tone and visible discoloration.','/facials.html'),
'brazilian-waxing-clearfield-ut.html':('Brazilian Waxing Clearfield UT','Brazilian Waxing','Professional waxing with preparation, comfort and aftercare guidance.','/waxing.html'),
'underarm-waxing-in-clearfield-ut.html':('Underarm Waxing Clearfield UT','Underarm Waxing','Efficient underarm waxing with skin-sensitivity and aftercare considerations.','/waxing.html'),
'eyebrow-waxing-in-clearfield-ut.html':('Eyebrow Waxing Clearfield UT','Eyebrow Waxing','Brow shaping based on natural growth and preferred definition.','/waxing.html'),
'back-waxing-clearfield-ut.html':('Back Waxing Clearfield UT','Back Waxing','Professional back waxing with preparation and post-service skin-care guidance.','/waxing.html'),
'classiclashes.html':('Classic Lashes Clearfield UT','Classic Eyelash Extensions','A defined lash set designed around natural lash condition and preferred length.','/eyelashextensions.html'),
'hybrid-lashes.html':('Hybrid Lashes Clearfield UT','Hybrid Eyelash Extensions','A blended lash style combining classic definition with added texture.','/eyelashextensions.html'),
'volume-lashes.html':('Volume Lashes Clearfield UT','Volume Eyelash Extensions','A fuller style created with lightweight fans selected for the natural lashes.','/eyelashextensions.html'),
'lashlifttint.html':('Lash Lift and Tint Clearfield UT','Lash Lift and Tint','A low-maintenance service that enhances the appearance of natural lashes.','/eyelashextensions.html'),
'prenatal-massage-clearfield-ut.html':('Prenatal Massage Clearfield UT','Prenatal Massage','Pregnancy-aware massage with screening, positioning and pressure modifications.','/massage.html'),
'hot-stone-massage.html':('Hot Stone Massage Clearfield UT','Hot Stone Massage','A relaxation-focused session using heated stones when appropriate for the client.','/massage.html'),
'deep-tissue-massage-clearfield.html':('Deep Tissue Massage Clearfield UT','Deep Tissue Massage','Focused massage pressure adjusted to tension patterns, comfort and health history.','/massage.html'),
'massage-therapy-clearfield-ut.html':('Massage Therapy Clearfield UT','Massage Therapy in Clearfield','Personalized massage sessions for relaxation and muscular tension.','/massage.html')
}
NAV='<header class="site-header"><div class="wrap header-row"><a class="logo" href="/">Hyde Beauty & Wellness</a><nav><a href="/laserhairremoval.html">Laser</a><a href="/botox.html">Injectables</a><a href="/facials.html">Facials</a><a href="/waxing.html">Waxing</a><a href="/massage.html">Massage</a><a class="btn" href="'+BOOK+'">Book Online</a></nav></div></header>'
for fn,(title,h1,desc,parent) in PAGES.items():
    html=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)} | Hyde Beauty & Wellness</title><meta name="description" content="{escape(desc)}"><link rel="canonical" href="https://www.hydemedspaclearfield.com/{fn}"><link rel="stylesheet" href="/styles.css"></head><body>{NAV}<main><section class="hero"><div class="wrap"><p>Hyde Beauty & Wellness Clearfield</p><h1>{escape(h1)}</h1><p>{escape(desc)}</p><a class="btn" href="{BOOK}">Book Online</a></div></section><section class="section"><div class="wrap"><h2>Personalized Treatment Planning</h2><p>Appointments begin with a review of goals, relevant history, preparation and expected aftercare. The provider determines whether the service is appropriate and explains realistic expectations, possible temporary effects and recommended timing.</p><p>Results and suitability vary by individual. Follow all instructions supplied by the licensed or trained professional responsible for the service.</p></div></section><section class="section alt"><div class="wrap"><h2>Related Services</h2><p><a href="{parent}">Return to the main service guide</a> · <a href="/meet-our-service-providers-clearfield.html">Meet providers</a> · <a href="/clearfield-spa.html">Clearfield location</a></p></div></section><section class="cta"><div class="wrap"><h2>Schedule in Clearfield</h2><p>189 S State St #160, Clearfield, UT 84015 · <a href="tel:3854215854">(385) 421-5854</a></p><a class="btn" href="{BOOK}">View Availability</a></div></section></main><footer><div class="wrap"><p>Hyde Beauty & Wellness Clearfield · Individual consultation required.</p></div></footer></body></html>'''
    (ROOT/fn).write_text(html,encoding='utf-8')
urls=['https://www.hydemedspaclearfield.com/']+[f'https://www.hydemedspaclearfield.com/{x}' for x in sorted(list(PAGES)+['laserhairremoval.html','botox.html','facials.html','waxing.html','eyelashextensions.html','massage.html','meet-our-service-providers-clearfield.html','clearfield-spa.html'])]
(ROOT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>{u}</loc></url>' for u in urls)+'</urlset>',encoding='utf-8')
print(f'Generated {len(PAGES)} supporting pages and {len(urls)} sitemap URLs')
