#!/usr/bin/env python3
from pathlib import Path
from html import escape
ROOT=Path(__file__).parent
BOOK='https://dashboard.boulevard.io/booking/businesses/9bf461e1-913f-4005-9f23-ac457d7a3747/widget#/locations'
BASE='https://www.hydemedspaclearfield.com'
PAGES={
'brazilian-laser-hair-removal-clearfield-ut.html':('Brazilian Laser Hair Removal Clearfield UT','Brazilian Laser Hair Removal','Consultation-based hair reduction for the Brazilian area with preparation, session timing and aftercare guidance.','/laserhairremoval.html'),
'underarm-laser-hair-removal-clearfield-ut.html':('Underarm Laser Hair Removal Clearfield UT','Underarm Laser Hair Removal','Reduce repeated shaving, dark shadow and irritation with a customized series of treatments.','/laserhairremoval.html'),
'arm-laser-hair-removal-clearfield-ut.html':('Arm Laser Hair Removal Clearfield UT','Arm Laser Hair Removal','Treatment planning for partial or full arms based on hair density, skin response and long-term goals.','/laserhairremoval.html'),
'facial-laser-hair-removal-in-clearfield-ut.html':('Facial Laser Hair Removal Clearfield UT','Facial Laser Hair Removal','Hair-reduction treatment for selected facial areas after review of skin, hair and medical history.','/laserhairremoval.html'),
'bikini-laser-hair-removal.html':('Bikini Laser Hair Removal Clearfield UT','Bikini Laser Hair Removal','Customized bikini-area hair reduction with preparation and aftercare instructions.','/laserhairremoval.html'),
'full-body-laser-hair-removal-clearfield-ut.html':('Full Body Laser Hair Removal Clearfield UT','Full Body Laser Hair Removal','Multi-area planning that coordinates treatment timing, preparation and maintenance.','/laserhairremoval.html'),
'mens-laser-hair-removal-clearfield-ut.html':("Men's Laser Hair Removal Clearfield UT","Men's Laser Hair Removal",'Hair-reduction options for common face and body areas after an individual consultation.','/laserhairremoval.html'),
'laser-hair-maintenance-clearfield-ut-long-term-hair-reduction-at-hyde-beauty-wellness.html':('Laser Hair Maintenance Clearfield UT','Laser Hair Removal Maintenance','Maintenance planning based on regrowth, treatment history and the area treated.','/laserhairremoval.html'),
'forehead-botox.html':('Forehead Botox Clearfield UT','Forehead Botox','Personalized neuromodulator planning based on forehead movement, symmetry and desired softening.','/botox.html'),
'crows-feet-botox.html':("Crow's Feet Botox Clearfield UT","Crow's Feet Treatment",'Consultation and treatment planning for expression lines around the eyes.','/botox.html'),
'jawline-botox.html':('Jawline Botox Clearfield UT','Jawline and Masseter Botox','Individual assessment for jawline balance, masseter concerns and appropriate treatment goals.','/botox.html'),
'natural-lip-filler.html':('Natural Lip Filler Clearfield UT','Natural-Looking Lip Filler','Consultation-based lip enhancement focused on proportion, balance and individualized results.','/botox.html'),
'lip-flip-clearfield-ut.html':('Lip Flip Clearfield UT','Lip Flip Consultation','Neuromodulator-based lip-flip planning after assessment of movement and desired outcome.','/botox.html'),
'dysport-clearfield-ut.html':('Dysport Clearfield UT','Dysport Treatments','Consultation-driven wrinkle treatment using Dysport when appropriate for the client.','/botox.html'),
'sculptra-clearfield-ut.html':('Sculptra Clearfield UT','Sculptra Consultation','Collagen-stimulator consultation focused on candidacy, treatment sequence and realistic timing.','/botox.html'),
'microneedling.html':('Microneedling Clearfield UT','Microneedling','Controlled skin treatment planned around texture, tone, treatment history and recovery time.','/facials.html'),
'rf-microneedling-clearfield-ut.html':('RF Microneedling Clearfield UT','RF Microneedling','Radiofrequency microneedling consultation for appropriate texture and firmness concerns.','/facials.html'),
'chemicalpeel.html':('Chemical Peels Clearfield UT','Chemical Peels','Professional peel selection based on skin type, current products, sensitivity and goals.','/facials.html'),
'hydrating-facial.html':('Hydrating Facial Clearfield UT','Hydrating Facial','A customized facial focused on cleansing, hydration and supporting the skin barrier.','/facials.html'),
'ipl-photofacial.html':('IPL Photofacial Clearfield UT','IPL Photofacial','Light-based consultation and treatment planning for appropriate tone and discoloration concerns.','/facials.html'),
'dermaplaning-clearfield-ut.html':('Dermaplaning Clearfield UT','Dermaplaning','Professional exfoliation planned around skin sensitivity, current products and goals.','/facials.html'),
'carbon-facial-clearfield-ut.html':('Carbon Facial Clearfield UT','Carbon Facial','A consultation-based facial option focused on cleansing, texture and visible skin refinement.','/facials.html'),
'glow-facial-clearfield-ut.html':('Glow Facial Clearfield UT','Glow Facial','A customized facial designed to support hydration, smoothness and a refreshed appearance.','/facials.html'),
'skin-care-products-hyde-beauty-and-wellness-clearfield.html':('Professional Skincare Products Clearfield UT','Professional Skincare Products','Product guidance based on skin type, treatment plan and daily routine.','/facials.html'),
'brazilian-waxing-clearfield-ut.html':('Brazilian Waxing Clearfield UT','Brazilian Waxing','Professional waxing with preparation, comfort and aftercare guidance.','/waxing.html'),
'underarm-waxing-in-clearfield-ut.html':('Underarm Waxing Clearfield UT','Underarm Waxing','Efficient underarm waxing with sensitivity and aftercare considerations.','/waxing.html'),
'eyebrow-waxing-in-clearfield-ut.html':('Eyebrow Waxing Clearfield UT','Eyebrow Waxing','Brow shaping based on natural growth and preferred definition.','/waxing.html'),
'back-waxing-clearfield-ut.html':('Back Waxing Clearfield UT','Back Waxing','Professional back waxing with preparation and post-service skin-care guidance.','/waxing.html'),
'classiclashes.html':('Classic Lashes Clearfield UT','Classic Eyelash Extensions','A defined lash set designed around natural lash condition and preferred length.','/eyelashextensions.html'),
'hybrid-lashes.html':('Hybrid Lashes Clearfield UT','Hybrid Eyelash Extensions','A blended lash style combining classic definition with added texture.','/eyelashextensions.html'),
'volume-lashes.html':('Volume Lashes Clearfield UT','Volume Eyelash Extensions','A fuller style created with lightweight fans selected for the natural lashes.','/eyelashextensions.html'),
'lashlifttint.html':('Lash Lift and Tint Clearfield UT','Lash Lift and Tint','A low-maintenance service that enhances the appearance of natural lashes.','/eyelashextensions.html'),
'prenatal-massage-clearfield-ut.html':('Prenatal Massage Clearfield UT','Prenatal Massage','Pregnancy-aware massage with screening, positioning and pressure modifications.','/massage.html'),
'hot-stone-massage.html':('Hot Stone Massage Clearfield UT','Hot Stone Massage','A relaxation-focused session using heated stones when appropriate for the client.','/massage.html'),
'deep-tissue-massage-clearfield.html':('Deep Tissue Massage Clearfield UT','Deep Tissue Massage','Focused pressure adjusted to tension patterns, comfort and health history.','/massage.html'),
'massage-therapy-clearfield-ut.html':('Massage Therapy Clearfield UT','Massage Therapy in Clearfield','Personalized massage sessions for relaxation and muscular tension.','/massage.html'),
'tattooremoval-clearfield.html':('Tattoo Removal Clearfield UT','Tattoo Removal Consultation','Consultation for tattoo characteristics, skin response, treatment timing and realistic expectations.','/services.html'),
'teethwhitening.html':('Teeth Whitening Clearfield UT','Teeth Whitening','Professional cosmetic whitening options with screening and aftercare guidance.','/services.html'),
'body-sculpting-services.html':('Body Sculpting Services Clearfield UT','Body Services','Consultation-based body services with candidacy, comfort and realistic outcome discussions.','/services.html'),
'wellness.html':('Wellness and Beauty Services Clearfield UT','Wellness and Beauty','Complementary beauty and wellness services available through the Clearfield location.','/services.html')
}
BLOG={
'botox-injections-clearfield-ut-nurse-injector-safe-natural-results-you-can-trust':('Botox Injections in Clearfield: Why Provider Training Matters','Botox is a medical aesthetic treatment. Provider training, facial assessment, dosing, placement and follow-up all influence safety and natural-looking results. A consultation should review goals, health history, facial movement and realistic expectations before treatment.','/botox.html'),
'forehead-botox-clearfield-ut-natural-expression':('Forehead Botox in Clearfield: Smoother Lines with Natural Expression','Forehead treatment planning should consider brow position, muscle strength, symmetry and the relationship between the forehead and frown-line muscles. Conservative planning can soften lines while maintaining natural movement.','/forehead-botox.html'),
'laser-hair-removal-explained-everything-you-need-to-know':('Laser Hair Removal: What to Know Before Starting','Hair grows in cycles, so a treatment series is typically needed. Preparation, sun exposure, skin response, hair color and the treatment area all affect planning. A consultation determines whether laser hair removal is appropriate.','/laserhairremoval.html'),
'custom-facials-based-on-your-unique-skin-type':('Choosing a Facial for Your Skin Type','A useful facial plan begins with current products, sensitivity, hydration, breakouts, pigmentation concerns and recent procedures. Professional assessment helps match exfoliation and treatment intensity to the skin.','/facials.html'),
'how-to-care-for-eyelash-extensions-tips-tricks':('How to Care for Eyelash Extensions','Gentle cleansing, avoiding unnecessary pulling, following fill timing and using lash-compatible products can help protect natural lashes and maintain the appearance of extensions.','/eyelashextensions.html'),
'waxing-frequency-how-often-should-you-go':('How Often Should You Schedule Waxing?','Waxing timing depends on the body area, growth cycle, skin response and personal preference. Consistent scheduling and appropriate home care can improve comfort and predictability.','/waxing.html')
}
NAV='<header class="site-header"><div class="wrap header-row"><a class="logo" href="/">Hyde Beauty & Wellness</a><nav><a href="/services.html">Services</a><a href="/laserhairremoval.html">Laser</a><a href="/botox.html">Injectables</a><a href="/facials.html">Facials</a><a href="/blog">Blog</a><a class="btn" href="'+BOOK+'">Book Online</a></nav></div></header>'
FOOT='<footer><div class="wrap"><p>Hyde Beauty & Wellness Clearfield · 189 S State St #160, Clearfield, UT 84015 · <a href="tel:+13854215854">(385) 421-5854</a></p><p><a href="/privacy-policy.html">Privacy</a> · <a href="/terms.html">Terms</a></p><small>Educational information only. Results and eligibility vary.</small></div></footer>'
def page(title,h1,desc,parent):
 return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)} | Hyde Beauty & Wellness</title><meta name="description" content="{escape(desc)}"><link rel="canonical" href="{BASE}/{title_slug}"><link rel="stylesheet" href="/styles.css"></head><body>{NAV}<main><section class="hero"><div class="wrap"><p>Hyde Beauty & Wellness Clearfield</p><h1>{escape(h1)}</h1><p>{escape(desc)}</p><a class="btn" href="{BOOK}">Book Online</a></div></section><section class="section"><div class="wrap"><h2>Personalized Planning</h2><p>Appointments begin with a review of goals, relevant history, preparation and expected aftercare. The provider determines whether the service is appropriate and explains realistic expectations, possible temporary effects and recommended timing.</p><p>Results and suitability vary by individual. Follow all instructions supplied by the licensed or trained professional responsible for the service.</p></div></section><section class="section alt"><div class="wrap"><h2>Related Services</h2><p><a href="{parent}">Main service guide</a> · <a href="/meet-our-service-providers-clearfield.html">Meet providers</a> · <a href="/clearfield-spa.html">Clearfield location</a></p></div></section><section class="cta"><div class="wrap"><h2>Schedule in Clearfield</h2><a class="btn" href="{BOOK}">View Availability</a></div></section></main>{FOOT}</body></html>'''
for fn,(title,h1,desc,parent) in PAGES.items():
 title_slug=fn
 (ROOT/fn).write_text(page(title,h1,desc,parent),encoding='utf-8')
blogdir=ROOT/'blog'; blogdir.mkdir(exist_ok=True)
items=[]
for slug,(title,summary,parent) in BLOG.items():
 html=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)} | Hyde Beauty & Wellness</title><meta name="description" content="{escape(summary)}"><link rel="canonical" href="{BASE}/blog/{slug}"><link rel="stylesheet" href="/styles.css"></head><body>{NAV}<main><section class="hero"><div class="wrap"><p>Hyde Clearfield Education</p><h1>{escape(title)}</h1><p>{escape(summary)}</p></div></section><section class="section"><div class="wrap"><h2>Planning Your Appointment</h2><p>Online information cannot determine individual candidacy. Discuss current medications, recent procedures, skin sensitivity, medical history and treatment goals with the responsible provider.</p><p><a href="{parent}">Read the related service guide</a> or <a href="{BOOK}">view appointment availability</a>.</p></div></section></main>{FOOT}</body></html>'''
 (blogdir/slug).write_text(html,encoding='utf-8')
 items.append(f'<article><h2><a href="/blog/{slug}">{escape(title)}</a></h2><p>{escape(summary)}</p></article>')
(blogdir/'index.html').write_text(f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Hyde Beauty & Wellness Clearfield Blog</title><meta name="description" content="Treatment education and beauty guidance from Hyde Beauty & Wellness Clearfield."><link rel="canonical" href="{BASE}/blog"><link rel="stylesheet" href="/styles.css"></head><body>{NAV}<main><section class="hero"><div class="wrap"><h1>Hyde Clearfield Treatment Education</h1><p>Clear, consultation-focused guidance for aesthetic, skincare, waxing, lash and laser services.</p></div></section><section class="section"><div class="wrap">{''.join(items)}</div></section></main>{FOOT}</body></html>''',encoding='utf-8')
core=['','services.html','about-us.html','contact-us.html','privacy-policy.html','terms.html','laserhairremoval.html','botox.html','facials.html','waxing.html','eyelashextensions.html','massage.html','meet-our-service-providers-clearfield.html','clearfield-spa.html']
urls=[BASE+'/'+x for x in core]+[f'{BASE}/{x}' for x in sorted(PAGES)]+[BASE+'/blog']+[f'{BASE}/blog/{x}' for x in sorted(BLOG)]
(ROOT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>{u}</loc></url>' for u in urls)+'</urlset>',encoding='utf-8')
print(f'Generated {len(PAGES)} treatment pages, {len(BLOG)} articles and {len(urls)} sitemap URLs')
